### ISSUE TITLE
Subject in Cancer Related Radiation Procedure pointing to US Core Patient

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/fsh-mcode#107]
Should the subject point to CancerPatient instead or was this discrepancy intended? If intended, it's unclear when to use the CancerPatient profile vs. US Core Patient.

**Comment by mlterryMitre-zz** [comment]
@rutemartins - yeh, it should be CancerPatient when the profile is "Cancer-related...".  We might be able to squeeze this in prior to STU publication.

**Comment by CarolinePotteiger** [comment]
This fix is included in mCODE 1.0
