### ISSUE TITLE
mCODE extensions are missing examples

### ISSUE THREAD

**Issue by mlterryMitre-zz** [standardhealth/fsh-mcode#116]
Identified by Lloyd McKenzie during the FMG mCODE Publication Review:
Warnings that the following extensions are missing examples:
* mcode-termination-reason
* mcode-laterality
* mcode-histology-morphology-behavior

Fixes are to represent these in at least one mCODE instance which has this in their profile.

**Comment by markkramerus** [comment]
Added in final 1.0 build
