### ISSUE TITLE
FHIR examples are not appearing in the Examples tab within each profile page

### ISSUE THREAD

**Issue by mlterryMitre-zz** [standardhealth/fsh-mcode#28]
Screenshot below:
![image](https://user-images.githubusercontent.com/40579130/72939217-78110400-3d3a-11ea-927b-80f6237017d8.png)

**Comment by cmoesel** [comment]
It looks like we need to update the ImplementationGuide JSON to use `exampleCanonical` (with a URL for the structdef) rather than `exampleBoolean`.  We can fix this in SUSHI, but since you're manually managing your ImplementationGuide JSON, you'll need to manually update that file.

**Comment by mlterryMitre-zz** [comment]
Thanks @cmoesel - @markkramerus - rolled fixes into fsh-mcode PR#30. https://github.com/standardhealth/fsh-mcode/pull/30

**Comment by markkramerus** [comment]
Fixed. Confirmed.
