### ISSUE TITLE
GenomicRegionStudied, UnitsOfLengthVS, and USCore SUSHI 0.6.1 compilation errors

### ISSUE THREAD

**Issue by mlterryMitre-zz** [standardhealth/fsh-mcode#31]
SUSHI 0.6.1 improved and found the following fsh syntax related grammar errors:

- `error: extraneous input 'GeneStudied' expecting {<EOF>, KW_ALIAS, KW_PROFILE, KW_EXTENSION, KW_INSTANCE, KW_INVARIANT, KW_VALUESET, KW_CODESYSTEM}`

- `error: Alias USCoreRace cannot be redefined to http://hl7.org/fhir/us/core/StructureDefinition/us-core-race; it is already defined as http://hl7.org/fhir/us/core/ValueSet/omb-race-category.`

- `error: extraneous input 'UCUM#mm' expecting {<EOF>, KW_ALIAS, KW_PROFILE, KW_EXTENSION, KW_INSTANCE, KW_INVARIANT, KW_VALUESET, KW_CODESYSTEM}`

**Comment by mlterryMitre-zz** [comment]
@markkramerus - PR#30 (https://github.com/standardhealth/fsh-mcode/pull/30) created which contains fixes.

**Comment by markkramerus** [comment]
Confirmed fixes for each issue. Closing.
