### ISSUE TITLE
Should component[DNARangesExamined] be a Range?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#32]
This refers to the GenomicRegionStudied profile, the component DNARangeExamined is a Range. The Range data type has a low and high element, whose type is SimpleQuantity. Is a SImpleQuality really suitable for a DNARange lower or upper bound?

**Comment by mlterryMitre-zz** [comment]
Done to align with the HL7 CG Reporting IG STU1 release which constrains the data type to Range: http://hl7.org/fhir/uv/genomics-reporting/region-studied.html.  If we change it, we break compatibility.

**Comment by markkramerus** [comment]
Understood, but is it *right*? Is it a question to raise on zulip for the genomics wg?

**Comment by mlterryMitre-zz** [comment]
imho, yes, I think it has to be a range. It has no meaning with only one quantity.

**Comment by markkramerus** [comment]
I don't think I'm making myself clear.  How is the start position given? In terms of a number, e.g., the number of base pairs from some other landmark (an integer), or something else?

**Comment by mlterryMitre-zz** [comment]
it's 2 integers... a number for start position (which is an integer) and a number for end position (which is also an integer).  It's a dna region for which variants are identified. Simple as that.  I'll enhance the GenomicRegionStudied example to illustrate in a future PR.

**Comment by mlterryMitre-zz** [comment]
If you only know one exact location, then the example the CGWG created within their GenomicsReport IG uses the `low` property of the range data type.

**Comment by markkramerus** [comment]
Closing. I see this is a count, so quantity is correct.
