### ISSUE TITLE
GeneticTestMethodVS constraint missing from TumorMarker profile.

### ISSUE THREAD

**Issue by mlterryMitre-zz** [standardhealth/fsh-mcode#41]
Missed porting this over from CIMPL.

**Comment by mlterryMitre-zz** [comment]
GeneticTestMethodVS was removed on purpose so that the `GeneticVariant` profile better aligns with the CG Reporting IG which ties this to the LOINC answer list.
Instead the change is actually to specify the binding of method to the LOINC answer list,  https://fhir.loinc.org/ValueSet/LL4048-6 (extensible)

**Comment by markkramerus** [comment]
I don't think this is the correct URL for LOINC lists. It should be: http://loinc.org/vs/LL4048-6. See https://www.hl7.org/fhir/loinc.html#alist

**Comment by mlterryMitre-zz** [comment]
Changed VS.
