### ISSUE TITLE
Inconsistent guidance on representing AJCC version 8 

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#44]
Our staging examples specify AJCC version 8 as follows:
`* method = MTH#C146985 "AJCC Cancer Staging Manual 8th Edition"`
However, our documentation states: "Because SNOMED CT does not currently have a code representing AJCC Version 8, specify the exact text 'AJCC Version 8' in the text sub-field of the code structure, and omit the code."
We need to have consistency between the guidance and the examples.

**Comment by mlterryMitre-zz** [comment]
PR merged. close issue.
