### ISSUE TITLE
Change one code in ConditionStatusTrendVS

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#51]
[Carmela]: Suggest removing `* SCT#260415000 "Not detected (qualifier)"` and adding `281900007 |No abnormality detected (finding)`.  This would be much more consistent with other values in the set, and also closer to the target meaning of "no evidence of disease".

**Comment by markkramerus** [comment]
PR # 60 merged. Keeping open until Caroline confirms the DD has been brought up to date.

**Comment by mlterryMitre-zz** [comment]
Re-opened. Forgot this needs to be changed in Data Dictionary.

**Comment by markkramerus** [comment]
Andre doesn't like this change. Trying to gather more opinions. Holding open.

**Comment by markkramerus** [comment]
One more suggestion for this, although debate exhaustion might be setting in: 
41647002 | No evidence of (contextual qualifier) (qualifier value) -- If we are going to use a qualifier, why not use this one, which is closer to "No Evidence of Disease".

**Comment by mlterryMitre-zz** [comment]
Changed VS term back to SCT#260415000 "Not detected (qualifier)" in ConditionStatusTrendVS based on feedback from Robert Miller. https://github.com/standardhealth/fsh-mcode/pull/67

**Comment by mlterryMitre-zz** [comment]
Reopened...forgot about Data Dictionary change again. :-)

**Comment by markkramerus** [comment]
Talked to Bob Miller about this. He didn't like the proposed code "No abnormality detected (finding)". He was neutral on SCT#260415000 "Not detected (qualifier)" versus SCT#41647002 | No evidence of (contextual qualifier) (qualifier value), so the sensible thing is to go back to SCT#260415000 "Not detected (qualifier)". Done & closing.
