### ISSUE TITLE
Remove RelationToLandmark and AnatomicalOrientation extensions on BodySite

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#59]
Remove extensions on BodySite (many profiles): unless these are specifically aligned with Clinical Genomics for GeneticSpecimen, none of the mCODE profiles go beyond specifying a value set for bodySite. There were ballot comments against extending bodySite.

NOTE: Leave laterality as-is because it addresses a ballot comment, and it is important MS element.

Ref #50

**Comment by mlterryMitre-zz** [comment]
fix in https://github.com/standardhealth/fsh-mcode/pull/65

**Comment by mlterryMitre-zz** [comment]
fix merged.
