### ISSUE TITLE
Proofread and if necessary correct the mCODE Diagram

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#69]
just a reminder to do this task -- with all our changes, we should be careful the diagram is accurate.

**Comment by mlterryMitre-zz** [comment]
Labeled blocked because Mark is the only person with the the Coggle diagram. This needs to be released moving forward or in a format that can be edited by the rest of the team.

**Comment by mlterryMitre-zz** [comment]
Fixed in https://github.com/standardhealth/fsh-mcode/pull/81
