### ISSUE TITLE
New batch of QA errors need to be addressed

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#70]
The new IG Pub has issued a boatload of new warnings and errors.

**Comment by cmoesel** [comment]
Most of the warnings about missing descriptions seem to be because we're not providing descriptions for our examples.  We don't currently support a way to have descriptions for examples in FSH, but we could.

**Comment by cmoesel** [comment]
The broken link errors look a lot like the ones we were getting on comments fields before.  They are links to things in the base specification that are erroneously pointing to our local IG instead of the FHIR site.  I think Grahame considers that a publisher error.

**Comment by mlterryMitre-zz** [comment]
issue is blocked for resolution if it's related to the IG Publisher.

**Comment by mlterryMitre-zz** [comment]
@markkramerus and @cmoesel - I don't see the broken link errors in QAReport using SUSHI 0.8.0,  IG Publisher version `FHIR IG Publisher Version 1.0.48-SNAPSHOT`, and the current FHIR templates (as of 2/12/20).
I'll close the ticket.   If you still see the issue, LMK and I'll re-open.
