### ISSUE TITLE
TNM Categories should be Must Support in Stage Group hasMember

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#71]
I think we wanted to do this but we were blocked by CIMPL limitations. These should definitely be MS.

**Comment by CarolinePotteiger** [comment]
Fixed in this PR https://github.com/standardhealth/fsh-mcode/pull/76

**Comment by CarolinePotteiger** [comment]
Fixed in this PR https://github.com/standardhealth/fsh-mcode/pull/76
