### ISSUE TITLE
Add Must Supports to CancerRelatedMedicationStatement

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#73]
We used to inherit MS flags from US Core, but US Core 3.1 no longer has a MedicationStatement profile, so we are inheriting directly from FHIR MedicationStatement. Two important MS that are missing:  effective[x] -- the start and stop time of the medication, the medication[x] -- the medication itself.

**Comment by CarolinePotteiger** [comment]
Fixed in this PR https://github.com/standardhealth/fsh-mcode/pull/76
