### ISSUE TITLE
Implementation page is out of date

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/fsh-mcode#88]
Several things on the implementation page are out of date. The Body Site description still refers to multiple extensions when we had landmark-related extension. Several other things (vitals, labs) need to be updated to reflect 1.0, as well. The entire page needs to be carefully looked at.
Includes checking all versions and all supporting documentation.

**Comment by mlterryMitre-zz** [comment]
Documentation changes updated in https://github.com/standardhealth/fsh-mcode/pull/97 and https://github.com/standardhealth/fsh-mcode/pull/98.
